### PR TITLE
Basic functionality to save and load passwords

### PR DESCRIPTION
**Pull request by igorkulman**
With this PR
- if you set Save password when connecting to a network the password will be saved in Keychain
- when connecting to the same network again, the saved password from Keychain will be used instead of asking for the password again

I also added a simple logger using os_log to know what is going on in the newly added class and cleanup up the network manager a bit.

### CODE REVIEW

**Comment by Goshin** [comment]
Many thanks, but we need to delay password saving until the connection is successfully established, or we can provide an interface to manage the saved networks so a mistyped password can be removed.

**Comment by igorkulman** [comment]
> Many thanks, but we need to delay password saving until the connection is successfully established, or we can provide an interface to manage the saved networks so a mistyped password can be removed.

So not saving the password immediatelly, but at this point https://github.com/zxystd/HeliPort/blob/master/HeliPort/NetworkInfo.swift#L109?

**Comment by Goshin** [comment]
Yes, maybe you can add a parameter for `class func connect(networkInfo: NetworkInfo)` to determine to save the password or not.

**Comment by igorkulman** [comment]
> Yes, maybe you can add a parameter for `class func connect(networkInfo: NetworkInfo)` to determine to save the password or not.

I think it need to be added to the "callback" as the form where you enter the password does not call the connect method of the network manager but the callback directly. I updated the PR.

**Comment by Goshin** [comment]
Thanks. I will merge it soon when I complete the `connect_network` API.

**Comment by igorkulman** [comment]
> Thanks. I will merge it soon when I complete the `connect_network` API.

Ideally test it before merging, the code base is quite hard to read so there is a chance I made a mistake, but my testing went fine.

Using Keychain is quite an annoyance, on Catalina it asks for permission, but it it probably tolerable to the user.

**Pull request merged**
