### PR TITLE
Added support for " Show "Wi-Fi: Looking for Networks..." when itlwm …

### PR DESCRIPTION
**Pull request by ErrorErrorError**
…is scanning" from https://github.com/zxystd/HeliPort/issues/21

- Fixed a leak where if there is more than one ethernet controller on Api.c

Working on adding the enhancements from https://github.com/zxystd/HeliPort/issues/21. As of now, I still need to figure out how to check if there is currently a network connected and get the SSID, especially if you close the app and open the app back up.

### CODE REVIEW

**Comment by williambj1** [comment]
The releases are a good catch, nice work.

This PR is definitely going to be merged, but I have to merge it after someone fixes the UI glitch (I tried but I'm not familiar with `constraint`), there's quite a lot of people using HeliPort right now and we don't want to introduce unnecessary arguments or reports from community and forums, hope you understand our situation.

**Comment by zxystd** [comment]
don't consider about the app state, the app state depends on the driver ieee80211 state, setup a timer and get the state by sState api, if current state is AUTH or ASSOC, the driver is authenticating, if the state is RUN, the driver is connected. you can get the connected info by calling sSTAinfo(I haven't handle it because i am busy now).

**Comment by ErrorErrorError** [comment]
> have to merge it after someone fixes the UI glitch (I tried but I'm not familiar with `constraint`)

No worries I understand! I am also checking on the glitch too in the meantime. 

Thank you guys for your amazing work!

**Comment by williambj1** [comment]
Thanks, I'll check the changes later.

**Pull request merged**
