### PR TITLE
Correctly converting RSSI to strength image

### LINKED ISSUE #43: [Bug] Network strength image always shows full strength
**Describe the bug**
If you open the menu and look at the list of networks, all of them have an icon representing full signal strength.

**To Reproduce**
1. Open the menu
2. Look at the strength icons of the networks

**Expected behavior**
Strength icons should represent the actual signal strength

**Screenshots**
Screenshot 2020-07-03 at 14 27 33

**Environment (please complete the following information):**
 - OS Version: 10.15.5
 - Software Version: `19c0386`

**Additional context**
Doing some quick debugging I think the problem is in https://github.com/zxystd/HeliPort/blob/master/HeliPort/Appearance/WiFiMenuItemView.swift#L179-L192. It expects negative values but it is always called with positive values.

### PR DESCRIPTION
**Pull request by igorkulman**
Fixes #43 

Before:
Screenshot 2020-07-03 at 14 27 33

After:
Screenshot 2020-07-03 at 14 34 26

### CODE REVIEW

**Comment by Goshin** [comment]
Thx. Wouldn't it be better to fix it in itlwm? so that it can correctly reflect the RSSI value. @zxystd

**Comment by igorkulman** [comment]
> Thx. Wouldn't it be better to fix it in itlwm? so that it can correctly reflect the RSSI value. @zxystd

Depends, maybe just working with positive values is easier in itlwm. Representing RSSI as positive vs negative values is mostly just a convention.

**Comment by naveenkrdy** [comment]
since latest commit on itlwm now rrsi is now properly calculated, so i guess this PR should be closed.

**Comment by williambj1** [comment]
Fixed in https://github.com/zxystd/itlwm/commit/dd4bec0a9ac209f4218914d63922409eab98be65

**Comment by Goshin** [comment]
Really appreciate your contribution. Feel free to reopen the PR if you would like to add another improvement or fix on the strength indicator.

**Pull request closed without merging**
